# Generated by Django 6.0.3 on 2026-03-21 21:43

import books.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('annee_publication', models.IntegerField()),
                ('langue', models.CharField(max_length=30)),
                ('statut', models.CharField(choices=[('actif', 'ACTIF'), ('archived', 'ARCHIVE')], max_length=12)),
                ('cover', models.ImageField(upload_to=books.models.rename_file)),
                ('authors', models.ManyToManyField(related_name='livresauthor', to='authors.authors')),
                ('categories', models.ManyToManyField(related_name='livres', to='categories.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Copies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquisition', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=12)),
                ('localisation', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('disponible', 'DISPONIBLE'), ('emprunte', 'EMPRUNTE'), ('reserve', 'RESERVE'), ('perdu', 'PERDU'), ('retire', 'RETIRE')], default='disponible', max_length=15)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='books.books')),
            ],
        ),
    ]
