# Generated by Django 6.0.3 on 2026-03-12 03:00

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '__first__'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('annee_publication', models.IntegerField()),
                ('langue', models.CharField(max_length=30)),
                ('statut', models.CharField(choices=[('actif', 'ACTIF'), ('archived', 'ARCHIVE')], max_length=12)),
                ('cover', models.ImageField(upload_to=books.models.rename_file)),
                ('authors', models.ManyToManyField(related_name='livresauthor', to='authors.authors')),
                ('categories', models.ManyToManyField(related_name='livres', to='categories.categories')),
            ],
        ),
    ]
