# Generated by Django 6.0.3 on 2026-03-12 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.CreateModel(
            name='Copies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquisition', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=12)),
                ('localisation', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('disponible', 'DISPONIBLE'), ('emprunte', 'EMPRUNTE'), ('reserve', 'RESERVE'), ('perdu', 'PERDU'), ('retire', 'RETIRE')], default='disponible', max_length=15)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.books')),
            ],
        ),
    ]
