# Generated by Django 6.0.3 on 2026-03-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_isbn_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copies',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='books.books'),
        ),
    ]
