# Generated by Django 6.0.3 on 2026-03-22 21:18

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='carte_etudiant',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.rename_etudiant_carte_file),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('librarian', 'Librarian'), ('member', 'Member')], default='member', max_length=9),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('bloque', 'Bloqué'), ('expire', 'Expiré'), ('attente', 'En attente')], default='actif', max_length=8),
        ),
    ]
