# Generated by Django 6.0.3 on 2026-03-22 23:23

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profil',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=members.models.rename_file),
        ),
    ]
