# Generated by Django 6.0.3 on 2026-03-24 13:23

import django.db.models.deletion
import members.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_customuser_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formule', models.CharField(choices=[('standard', 'STANDARD'), ('student', 'STUDENT'), ('premium', 'PREMIUM')])),
                ('status', models.CharField(choices=[('actif', 'ACTIF'), ('expired', 'EXPIRED')], default='actif')),
                ('date_deb', models.DateField(auto_now_add=True)),
                ('date_end', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
