# Generated by Django 6.0.3 on 2026-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_subscriptions_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='formule',
            field=models.CharField(),
        ),
    ]
