# Generated by Django 6.0.3 on 2026-03-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_subscriptions_formule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
