# Generated by Django 6.0.3 on 2026-03-30 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='status',
            field=models.CharField(choices=[('lost', 'LOST'), ('rendered', 'RENDERED'), ('lateness', 'LATENESS'), ('pending', 'PENDING')], default='pending'),
        ),
        migrations.AlterField(
            model_name='loans',
            name='date_back',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sold', 'SOLD'), ('nsold', 'NOT SOLD')], default='nsold')),
                ('amount', models.IntegerField()),
                ('emprunt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='penalty', to='loans.loans')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='loans.penalty')),
            ],
        ),
    ]
