# Generated by Django 6.0.3 on 2026-03-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('formule', models.CharField(max_length=50)),
                ('extended_count', models.IntegerField()),
                ('loan_days_duration', models.IntegerField()),
            ],
        ),
    ]
