# Generated by Django 6.0.3 on 2026-03-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanrules',
            name='lifetime',
            field=models.IntegerField(default=365),
        ),
        migrations.AlterField(
            model_name='subscriptionplanrules',
            name='formule',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
