# Generated by Django 6.0.3 on 2026-03-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_subscriptionplanrules_lifetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanrules',
            name='max_book',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
